steps:
  - id: "compile"
    name: "ubuntu"
    args: 
      - bash
      - ./compile.sh
  - id: "deploy index functionn"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["functions", "deploy", "index", "--entry-point=test", "--project=${_PROJECT}", "--trigger-http"]
    dir: bin/web/
substitutions:
  _PROJECT: open-contest-dev
