steps:
  - id: "compile"
    name: "sandrokeil/typescript"
    args: 
      - tsc
  - id: "Make code bucket"
    name: gcr.io/cloud-builders/gsutil
    args: ["mb", "-p", "${_PROJECT}", "gs://${_PROJECT}-code/"]
  - id: "deploy index function"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["functions", "deploy", "index", "--entry-point=test", "--project=${_PROJECT}", "--trigger-http"]
    dir: bin/web/
    waitFor: ["compile"]
substitutions:
    _PROJECT: open-contest-dev
