steps:
  - id: "Check account"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["auth", "list"]
  - id: "compile"
    name: "launcher.gcr.io/google/ubuntu16_04"
    args: 
      - bash
      - ./compile.sh
  - id: "deploy index function"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["functions", "deploy", "index", "--entry-point=test", "--project=open-contest-dev", "--trigger-http"]
    dir: bin/web/
substitutions:
  _PROJECT: open-contest-dev
