# steps:
#   # - id: "compile"
#   #   name: "sandrokeil/typescript"
#   #   args: 
#   #     - tsc
#   - id: "donothing"
#     name: "ubuntu"
#     args: ["echo", "''"]
#   # - id: "deploy index function"
#   #   name: "gcr.io/cloud-builders/gcloud"
#   #   args: ["functions", "deploy", "index", "--entry-point=test", "--project=${_PROJECT}", "--trigger-http", "--region=us-east1", "--memory=128MB", "--timeout=11s"]
#   #   dir: src/web/
#   #   waitFor: ["donothing"]
#   # - id: "deploy python runner"
#   #   name: "gcr.io/cloud-builders/gcloud"
#   #   args: ["functions", "deploy", "py2-runner", "--entry-point=run", "--project=${_PROJECT}", "--trigger-resource=${_PROJECT}-code-python2", "--region=us-east1", "--memory=512MB", "--timeout=60s", "--trigger-event=google.storage.object.finalize", "--runtime", "nodejs8"]
#   #   dir: src/backend/runners/python2/
#   #   waitFor: ["donothing"]
#   # - id: "deploy python runner"
#   #   name: "gcr.io/cloud-builders/gcloud"
#   #   args: ["beta", "functions", "deploy", "web-generator", "--entry-point=generate", "--project=${_PROJECT}", "--region=us-east1", "--memory=512MB", "--timeout=60s", "--runtime", "python37", "--set-env-vars", "WEB_BUCKET=contests-dev.nathantheinventor.com", "--trigger-http"]
#   #   dir: src/backend/web-generator/
#   #   waitFor: ["donothing"]
# substitutions:
#     _PROJECT: open-contest-dev
